### ISSUE TITLE
Pypi version

### ISSUE THREAD

**Issue by superalex** [Xof/django-pglocks#11]
Hello!,

I've seen the current version is 1.0.2 (with python3 support) and the pypi one is the 1.0.1, could you update pypi to the current version?

Thanks! :+1:

**Comment by Nesan** [comment]
:+1: on updating pypi with 1.0.2 version. Pretty please.

**Comment by Xof** [comment]
No one's offered a pull request for 1.0.2; I'll be happy to consider if someone would like to.

**Comment by Chronial** [comment]
@Xof Any update on this?
Would love to use a version from pypi

**Comment by superemily** [comment]
Another vote for this.

**Comment by jackdbernier** [comment]
1.0.2 was uploaded on 2016-07-07  https://pypi.python.org/pypi/django-pglocks

This issue could be closed.
