### ISSUE TITLE
Improve documentation and add advisory_xact_lock

### ISSUE THREAD

**Issue by lionel-panhaleux** [Xof/django-pglocks#15]
You can not protect database operations inside the advisory_lock context if you are running under Django transaction Middleware. The advisory_lock context is still good if you want to protect concurrent access to other resources (we use it to avoid stampede on some external resources)

For example, this code is as good as not locked:

``` python
with advisory_lock(42):
    obj = MyObject.get(id=42)
    obj.accessed +=1
    obj.save()
```

If you do not commit _inside_ the context, then with two workers you can get the following behavior:
- A takes lock
- B wait on lock
- A read obj, accessed = 0
- A write accessed = 1 (change not committed)
- A release lock
- B takes lock (this goes very fast since B was waiting for it)
- B read obj, accessed = 0 (A change still not committed : it takes time to build the response)
- A commits
- B writes accessed = 1
- B commits

We had a very ugly bug in production because we were on the wrong impression our databases transactions were protected inside the advisory_lock context.

We had to write own py2/3 compatible version of this, that I share with you here under MIT license https://gist.github.com/lionel-panhaleux/bd62ade43afe57e6f365 .

**Comment by Xof** [comment]
Thank you! I'll update the documentation to indicate that the locks are not compatible with the standard transaction middleware. In general, I don't advise the use of this module outside of explicit transactions.
