### ISSUE TITLE
Adding multiple locks per requests

### ISSUE THREAD

**Issue by jackdbernier** [Xof/django-pglocks#19]
postgres supports arrays, a query to get locks on multiple keys at once could look like

```
SELECT pg_advisory_lock(a) FROM unnest(ARRAY[1,2]) as a;
```

**Comment by Xof** [comment]
My first reaction to this is that it is probably encouraging bad behavior. While locks are not heavyweight per se, the number of entries in the lock table is limited, and an API that implies that they can be consumed in an unbounded way is not wise.

**Comment by jackdbernier** [comment]
Imagine that you have a process that needs to lock a set of keys (processing a group of elements), right now you'd have to request locks in loop (be done using https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack). This is in no way better with regard to maximum number of locks the server can hold. Though sending multiple keys at once would increase performances.

The documentation proposed
```
SELECT pg_advisory_lock(q.id) FROM
(
  SELECT id FROM foo WHERE id > 12345 LIMIT 100
)
```
and this is what inspired this feature request.

To your point, the feature should come with a warning that there is a limit to the number of locks a server can hold at any point in time which is a function of max_locks_per_transaction and max_connections.

**Comment by Xof** [comment]
I understand that the API doesn't support it right now, but that doesn't mean it *should* support it. If someone is locking a set of resources like that, row-level locking is a far better fit, especially given that the ORM now supports FOR UPDATE and SKIP LOCKED.

**Comment by jackdbernier** [comment]
That's assuming that you are locking exclusively elements represented using the django orm.

Would you reject a pull request if someone implemented it and added a few lines in the documentation about limitations?

**Comment by Xof** [comment]
I don't believe this is an appropriate feature for this API.
