### ISSUE TITLE
Update PyPI to make 'caniusepython3' pass

### ISSUE THREAD

**Issue by KlaasH** [Xof/django-pglocks#23]
PR #22 was merged, adding metadata so that `caniusepython3` would recognize that this package is compatible, but PyPI doesn't know about it yet, so the tool still flags this package as unsupported.  Since it's just a metadata change, it might not even rate a version change, but this at least needs to be published to PyPI to update the metadata.

**Comment by Xof** [comment]
Thanks. Needed a version bump, so done.
